### ISSUE TITLE
关于模型的训练模式

### ISSUE THREAD

**Issue by shaoyangxu** [yao8839836/text_gcn#114]
嘿，我想问一个问题: 如果我的语料比 20ng还要大几百倍，假如我把语料分成了几百份小语料，那我是需要创建几百个独立的GCN来对各自的小语料进行训练？还是说，我可以创建一个GCN，然后把几百份小语料看作是几百个batch，权重共享地进行训练？

**Comment by yao8839836** [comment]
@beiweixiaoxu 

应该是将小语料看作是几百个batch，共享权重，但要保证每一份的特征维度是一样的。

**Comment by shaoyangxu** [comment]
> @beiweixiaoxu
> 
> 应该是将小语料看作是几百个batch，共享权重，但要保证每一份的特征维度是一样的。



> @beiweixiaoxu
> 
> 应该是将小语料看作是几百个batch，共享权重，但要保证每一份的特征维度是一样的。

好的，感谢回复。
