### ISSUE TITLE
Validation accuracy is 0.000

### ISSUE THREAD

**Issue by Ketki-Savle** [yao8839836/text_gcn#28]
Hello, 

I am using this implementation on my corpus which is a collection of txt files. 

When running train.py I get good accuracy on train data but 0.000 accuracy on validation data. At the end all precision, recall and f-1 score is all 0. 

Could you please address this problem. 

Thank you.

**Comment by yao8839836** [comment]
Are your input files in the same format as the five example corpora in the project?

You can add print(val_size, test_size) in build_graph.py to see number of validation and test examples.

**Comment by Ketki-Savle** [comment]
Hello, 

Thank you for your quick response. My input files are not in the same format but I have adjusted the code. 

My data is : 181 folders in which I have multiple files. 
I first extract the data and for file labeling, I am using the file names. 
The class labels are binary 0 and 1 for each sample.
Every text file is a collection of 5 sentences on average. 

Are you also using the ids/names of all the files that you have in 20ng? Could you please elaborate more on this structure in your code? I am happy to share my code and data with you in email if that's ok. 

Thank you for your help.

**Comment by yao8839836** [comment]
@Ketki-Savle 

Hi, in data/20ng.txt:

data/20ng/20news-bydate-test/alt.atheism/53068	20news-bydate-test	alt.atheism
data/20ng/20news-bydate-test/alt.atheism/53257	20news-bydate-test	alt.atheism
data/20ng/20news-bydate-test/alt.atheism/53260	20news-bydate-test	alt.atheism
data/20ng/20news-bydate-test/alt.atheism/53261	20news-bydate-test	alt.atheism

each line is the meta data for a document. Each line has three columns separated by '\t'. The first column is the document path and name, you can traverse your 181 folders to get it. The second column is the train or test indicator for the document. The third column is the label (0 or 1 in your dataset) for the document.

In /data/corpus/20ng.txt , each line is the raw text for corresponding line in data/20ng.txt with out '\n', it means the first line without '\n' is the raw text in data/20ng/20news-bydate-test/alt.atheism/53068, and the second line without '\n' is the raw text in data/20ng/20news-bydate-test/alt.atheism/53257

Thanks.

**Comment by Ketki-Savle** [comment]
Hi, 

Thank you. This clears out some of my confusion. 

Now, in the coding: 

for doc_meta in shuffle_doc_name_list:
    temp[2] = doc_meta.split('\t')
    label_set.add(temp[2])
label_list = list(label_set)

Here should I extract class 0 and 1 in my case? 

So my label list is not the name of the document but the classes? 

Also, what should be the output of: 

y = []
for i in range(real_train_size):
    doc_meta = shuffle_doc_name_list[i]
    temp = doc_meta.split('\t')
    label = temp[0]
    one_hot = [0 for l in range(len(label_list))]
    label_index = label_list.index(label)
    one_hot[label_index] = 1
    y.append(one_hot)
y = np.array(y)

Should this y be all my document names or classes? 

Same goes for ty and eventually ally. 

I truly appreciate your help on this one. I will run your code on 20ng too and compare the values of each variable. Please confirm my doubts above and I know we can solve this :)

**Comment by yao8839836** [comment]
@Ketki-Savle 

Hi,

temp[2] is 0 or 1 in your case, label_list is classes list of your document.

y is the one hot label vectors (each vector is [0,1] or [1,0]) for your training documents (excluding validation documents).

ty is one-hot label vectors for test documents and ally is one-hot label vectors for all word and nodes excluding test documents.

Thanks.

**Comment by Ketki-Savle** [comment]
Hi, 

Thank you for this information. 
I will correct my code and share the behavior. 

Truly appreciate your help. 
Regards,

**Comment by Ketki-Savle** [comment]
Hi, 

ally is one-hot label vectors for all words and nodes:
Do you mean to say that 0/1 label for all train documents? Plus for vocab, I do not have any labels for words so this is giving me all 0. Is this correct? 

Thank you.

**Comment by yao8839836** [comment]
@Ketki-Savle 

Yes, that is correct.

**Comment by Ketki-Savle** [comment]
Alright. I will get back to you. Thank you. :)

**Comment by Ketki-Savle** [comment]
Hey it worked!!

Thank you for all your help and patience! Seriously appreciate it. 

Regards, 
Ketki

**Comment by yao8839836** [comment]
@Ketki-Savle 

Great!
