### ISSUE TITLE
Cannot run your code correctly. 

### ISSUE THREAD

**Issue by Ketki-Savle** [yao8839836/text_gcn#29]
Hi, 

Creating a separate discussion for this issue: 

When I try to reproduce the results of 20ng to understand the output of every variable then absolutely at the beginning I get this error: 

**Your code:** 

if len(sys.argv) != 2:
	sys.exit("Use: python build_graph.py <dataset>")

datasets = ['20ng', 'R8', 'R52', 'ohsumed', 'mr']

dataset = sys.argv[1]

if dataset not in datasets:
	sys.exit("wrong dataset name")

**Error**: 

Traceback (most recent call last):

  File "<ipython-input-10-cd1ad1d58978>", line 3, in <module>
    dataset = sys.argv[1]

IndexError: list index out of range

SystemExit: Use: python build_graph.py <dataset>

I am using Spyder for the same. Checked online and looks like this could be IDE associated but when I tried running the code on cluster then also it gives me an error -

Use: python build_graph.py <dataset>

What am I doing wrong? Could you please help. 

Regards, 
Ketki

**Comment by yao8839836** [comment]
Please use 'python build_graph.py 20ng' instead as ReadME

**Comment by Ketki-Savle** [comment]
Hi, 

Did that but facing issues further. 

Please be patient with me. I will check why this code is not running smooth.

**Comment by Ketki-Savle** [comment]
Do you have any user who ran this in Spyder? 

Also, in the command: f = open('data/' + dataset + '.txt', 'r')

My understanding is : Navigate to the data folder and read 20ng dataset but inside that there are other folders. It is unable to locate the files further.

**Comment by Ketki-Savle** [comment]
Hi, 

It was a silly issue between absolute and relative path. Please ignore. :) 

Running your graph was a lot more easier to compare and understand what is going on. Thank you for your help and patience.
