### ISSUE TITLE
Preprocessing data script.

### ISSUE THREAD

**Issue by monk1337** [yao8839836/text_gcn#4]
Hello,
I tried with 20ng and it's working fine. But I am confuse how someone will  use that preprocessing script direct on text data which is not 20ng format data?
I wanted a simple example so if my sentence and labels are : 

sentences = [ 'Would you like a plain sweater or something else?​' , 'Great. We have some very nice wool slacks over here. Would you like to take a look?' ]

labels =       ['Yes' , 'No' ]

can you provide simple script to convert this data for graph network so It'll be very easy for those who want to apply gcn on text data since most of data are in csv format so simple script will be very useful. and I don't think any other data have 20ng format ( index and links etc )

Thanks :)

**Comment by yao8839836** [comment]
@monk1337 

Hi, I add prepare_data.py which can convert your example to the input of remove_words.py and build_graph.py

**Comment by monk1337** [comment]
That work  like charm , Thanks for quick reply Yao.
