### ISSUE TITLE
预测阶段，训练数据是否用到？预测阶段一定要输入训练数据吗？

### ISSUE THREAD

**Issue by guotong1988** [yao8839836/text_gcn#91]
训练数据的label是mask的

@yao8839836 

多谢！！！

**Comment by yao8839836** [comment]
@guotong1988 

原始GCN训练时，测试节点(没有label)也在图中跟着训练节点一起训练，一起更新embedding,。测试时就不需要训练数据了，只用到测试节点在训练时得到的最上层embedding, 维度等于标签个数，取最大那个即可。mask只是为了标明哪些点是测试点。

**Comment by guotong1988** [comment]
醍醐灌顶，悬崖勒马，多谢多谢
