### ISSUE TITLE
使GNN从Transductive到Inductive的最大改动是？ 或者说GNN里Inductive和Transductive的最大区别是？

### ISSUE THREAD

**Issue by guotong1988** [yao8839836/text_gcn#92]
感觉都是输入全图然后mask测试集的label，
就是sample上的区别？
@yao8839836 谢谢！

**Comment by yao8839836** [comment]
@guotong1988 

最大的区别：测试集是否加入了训练过程，inductive时，训练feed_dict只输入了训练子图，而不包含测试节点。是否采样不影响inductive和Transductive。

**Comment by guotong1988** [comment]
跪谢跪谢
