### ISSUE TITLE
训练R8数据集时，显示 RuntimeError: `sparse_placeholder` is not compatible with eager execution.

### ISSUE THREAD

**Issue by ZihanChen1995** [yao8839836/text_gcn#98]
您好，我在尝试数据集R8时，第一步 `python remove_words.py R8` 和第二步 ` python build_graph.py R8` 都很顺利。但是在进行第三步 `python train.py R8` 时，显示了如下错误：

```
...
(15361, 12730)	1.3204861225679978
(15361, 12970)	3.0645628376504432
(15361, 13153)	2.34231552100788
(15362, 15362)
(15362, 15362)

Traceback (most recent call last):
  File "train.py", line 77, in <module>
    'support': [tf.sparse_placeholder(tf.float32) for _ in range(num_supports)],
  File "train.py", line 77, in <listcomp>
    'support': [tf.sparse_placeholder(tf.float32) for _ in range(num_supports)],
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/array_ops.py", line 3093, in sparse_placeholder
    raise RuntimeError("`sparse_placeholder` is not compatible with "
RuntimeError: `sparse_placeholder` is not compatible with eager execution.
```
能请问下这个问题发生的原因是什么吗？ 万分感谢。

（运行环境：Google Colab
使用的TensorFlow版本: `tensorflow.compat.v1`）

**Comment by ZihanChen1995** [comment]
您好，我通过语句这个解决了这个问题: `tf.compat.v1.disable_eager_execution()`。似乎是TensorFlow版本导致的错误。

**Comment by muzimua** [comment]
> 
（运行环境：Google Colab
使用的 TensorFlow 版本tensorflow.compat.v1：）
您好，我在Google Colab运行python train.py R8遇到了和您一样的报错，请问您说的tf.compat.v1.disable_eager_execution()这个修改具体是替换哪一部分的代码呢？非常希望得到您的帮助

**Comment by muzimua** [comment]
> 您好，我通过这个句子解决了这个问题：`tf.compat.v1.disable_eager_execution()`。好像是 TensorFlow 版本导向致的错误。

（运行环境：Google Colab
使用的TensorFlow版本: tensorflow.compat.v1）您好，我在Google Colab运行python train.py R8遇到了同样的报错，请问您具体是用“tf.compat.v1.disable_eager_execution()”这段代码替换的哪一部分的代码呢？非常希望得到您的回复，感谢！

**Comment by muzimua** [comment]
> > 您好，我通过这个句子解决了这个问题：`tf.compat.v1.disable_eager_execution()`。好像是 TensorFlow 版本导向致的错误。
> 
> （运行环境：Google Colab 使用的TensorFlow版本: tensorflow.compat.v1）您好，我在Google Colab运行python train.py R8遇到了同样的报错，请问您具体是用“tf.compat.v1.disable_eager_execution()”这段代码替换的哪一部分的代码呢？非常希望得到您的回复，感谢！

直接将 tf.compat.v1.disable_eager_execution() 这段代码加在77行前面就解决了该问题

**Comment by Epsilon-Alpha-Beta** [comment]
> > > 您好，我通过这个句子解决了这个问题：`tf.compat.v1.disable_eager_execution()`。好像是 TensorFlow 版本导向致的错误。
> > 
> > 
> > （运行环境：Google Colab 使用的TensorFlow版本: tensorflow.compat.v1）您好，我在Google Colab运行python train.py R8遇到了同样的报错，请问您具体是用“tf.compat.v1.disable_eager_execution()”这段代码替换的哪一部分的代码呢？非常希望得到您的回复，感谢！
> 
> 直接将 tf.compat.v1.disable_eager_execution() 这段代码加在77行前面就解决了该问题

感谢您，我也遇到了此问题。通过您的提示解决了
