### ISSUE TITLE
构图时怎么用GPU

### ISSUE THREAD

**Issue by bp20200202** [yao8839836/text_gcn#99]
您好，我在服务器上运行您的程序时（使用R8数据集，也用os.environ["CUDA_VISIBLE_DEVICES"] ="3"指定了GPU号），在运行build_graph文件时不用GPU构图，只是用了CPU去构图，想问这是为什么

**Comment by yao8839836** [comment]
@bp20200202 

您好，构图时不涉及深度学习中矩阵计算等可以并行加速的操作，因此没用GPU。

**Comment by bp20200202** [comment]
> @bp20200202
> 
> 您好，构图时不涉及深度学习中矩阵计算等可以并行加速的操作，因此没用GPU。

那请问有没有构图可以用GPU的方法，这样运行起来真的好慢。还有当时您完成这些构图的时候花了多长时间

**Comment by yao8839836** [comment]
@bp20200202 CPU核数够多可以考虑多线程。20ng大概几分钟。

**Comment by bp20200202** [comment]
> @bp20200202 CPU核数够多可以考虑多线程。20ng大概几分钟。

好的，我尝试一下，谢谢

**Comment by bp20200202** [comment]
> @bp20200202 CPU核数够多可以考虑多线程。20ng大概几分钟。

请问可以发一下用了多线程的代码吗？我改不出来，感觉效率没有变化，可以的话麻烦发到sdbaip@163.com，谢谢了

**Comment by bp20200202** [comment]
> @bp20200202 CPU核数够多可以考虑多线程。20ng大概几分钟。

可以的话能麻烦您给我发一下加了线程的代码吗？我加的不对，实在弄不出来了，可以的话请发到sdbaip@163.com，谢谢

**Comment by yao8839836** [comment]
@bp20200202 

我也没有写过多线程的，但主要耗时在遍历所有滑动窗口，也就是build_graph.py的409--428行。

思路是对于409--428行，将所有滑动窗口分给N个线程，每个线程一个计数器，然后汇总计数器。

还有一个简单的加速方法是减小build_graph.py的380行的window_size = 20，将20改成5.

**Comment by bp20200202** [comment]
> @bp20200202
> 
> 我也没有写过多线程的，但主要耗时在遍历所有滑动窗口，也就是build_graph.py的409--428行。
> 
> 思路是对于409--428行，将所有滑动窗口分给N个线程，每个线程一个计数器，然后汇总计数器。
> 
> 还有一个简单的加速方法是减小build_graph.py的380行的window_size = 20，将20

**Comment by bp20200202** [comment]
> @bp20200202
> 
> 我也没有写过多线程的，但主要耗时在遍历所有滑动窗口，也就是build_graph.py的409--428行。
> 
> 思路是对于409--428行，将所有滑动窗口分给N个线程，每个线程一个计数器，然后汇总计数器。
> 
> 还有一个简单的加速方法是减小build_graph.py的380行的window_size = 20，将20改成5.

好的，谢谢啦，我再看看，最近我电脑也不知道咋回事，运行的比以前快了，我也没弄，
